site_name: tarator
site_description: Backend for Tarator Supplier Finder
repo_url: https://github.com/Tarator-Supplier/tarator-backend
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/Tarator-Supplier">Tarator-Supplier</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
